// Threat Intelligence Data - Auto-generated by fetch_threat_intel.py
// DO NOT EDIT MANUALLY - This file is automatically updated
// Last generated: 2025-11-16T22:31:11.604924+05:30

const threatIntelData = {
    "lastUpdated": "2025-11-16T22:31:11.604910+05:30",
    "comparisonPeriod": "",
    "hourlyThreats": [],
    "dailySummary": {}
};
