// Threat Intelligence Data - Auto-generated by fetch_threat_intel.py
// DO NOT EDIT MANUALLY - This file is automatically updated
// Last generated: 2025-11-16T22:18:38.423423+05:30

const threatIntelData = {
    "lastUpdated": "2025-11-16T22:18:38.423411+05:30",
    "comparisonPeriod": "",
    "hourlyThreats": [],
    "dailySummary": {}
};
